---
abstract: 'Swish3 KinoSearch backend'
author:
  - 'Peter Karman <karman at cpan dot org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120530'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SWISH-Prog-KSx
no_index:
  directory:
    - t
    - inc
requires:
  KinoSearch: 0.313
  Path::Class::File::Lockable: 0
  Path::Class::File::Stat: 0.03
  SWISH::3: 1
  SWISH::Prog: 0.55
  Search::Query: 0.17
  Search::Query::Dialect::KSx: 0.12
  Sort::SQL: 0.06
  Test::More: 0
  perl: 5.008003
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=SWISH-Prog-KSx
  homepage: http://dev.swish-e.org/wiki/perl
  license: http://dev.perl.org/licenses/
  repository: http://svn.swish-e.org/perl/SWISH-Prog-KSx/
version: 0.21
