--- #YAML:1.0
name:               SWISH-Prog-KSx
version:            0.05
abstract:           Swish3 KinoSearch backend
author:
    - Peter Karman <karman at cpan dot org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    KinoSearch:   0.30_07
    perl:         5.008003
    SWISH::3:     0.04
    SWISH::Prog:  0.32
    Test::More:   0
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/Bugs.html?Dist=SWISH-Prog-KSx
    homepage:    http://dev.swish-e.org/wiki/perl
    license:     http://dev.perl.org/licenses/
    repository:  http://svn.swish-e.org/perl/SWISH-Prog-KSx/
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
